EXP_NAME: "ant"

DMP:
  UNROLL_LENGTH: 5
  INFER_STATE: true

ENV:
  ENV_NAME: "ant"

TRAIN:
  NUM_TIMESTEPS: 1e8
  NUM_ENVS: 128
  LEARNING_RATE: 3.0e-4
  UNROLL_LENGTH: 10
  BATCH_SIZE: 1024
  NUM_MINIBATCHES: 32
  DISCOUNTING: 0.97

LOG:
  SAVE_PARAMS: false
  FREQUENCY: 200
