EXP_NAME: "walker2d"

DMP:
  UNROLL_LENGTH: 5
  INFER_STATE: true

ENV:
  ENV_NAME: "walker2d"

TRAIN:
  NUM_TIMESTEPS: 5e7
  NUM_ENVS: 128
  LEARNING_RATE: 3.0e-4
  UNROLL_LENGTH: 10
  BATCH_SIZE: 256
  NUM_MINIBATCHES: 32
  DISCOUNTING: 0.97
  REWARD_SCALING: 0.1

LOG:
  SAVE_PARAMS: false
  FREQUENCY: 200
